apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hpccsystems-fullname" . }}
  labels:
    app: {{ include "hpccsystems-name" . }}
    chart: {{ include "hpccsystems-chart" . }}
    release: {{ .Release.Name }}
data:
  topology.properties: |
    thor1.name=t1
    thor1.eclagent=myeclagent
    thor1.eclccserver=myeclccserver
    thor1.eclscheduler=myeclscheduler

    roxie1.name=r1
    #Will use default values for the rest
    #
    #roxie2.name=r2

  {{- if (eq "aws" .Values.cloud.type) }}
  roxie.properties: |
    default.roxieMulticastEnabled=false
  {{- end }}

